pull_request_rules:
  - name: automatic merge for pre-commit ci updates
    conditions:
      - author=pre-commit-ci[bot]
      - title=[pre-commit.ci] pre-commit autoupdate
    actions:
      merge:
        method: squash
