name: Auto Update pre-commit
# Update pre-commit config and create PR if changes are detected
# OG author: Christoph Fröhlich <christoph.froehlich@ait.ac.at>[ROS2 Control CI]
# UoE editor: Alejandro Bordallo <alex.bordallo@ed.ac.uk>

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 2 * *'  # Runs at 00:00, on day 2 of the month

jobs:
  auto_update_and_create_pr:
    uses: ./.github/workflows/reusable-update-pre-commit.yml
    secrets:
      precommit-pr-token: ${{ secrets.PRECOMMIT_AUTOUPDATE_PR_TOKEN }}
